In [1]:
import numpy as np

This will create a 1-D Array

In [4]:
a = np.zeros(5)  # Return a new array of given shape and type, filled with zeros.

In [6]:
a

array([0., 0., 0., 0., 0.])

In [8]:
a.ndim

1

This will create a 2-D Array

In [10]:
b = np.zeros((3, 4))

In [12]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
b.ndim

2

In [14]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

3-D Arrays which means 3 inputs and 3 square brackets


In [15]:
arr = np.zeros((1, 3, 4))
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])