In [ ]:
import numpy as np

In [ ]:
arr1 = np.random.randint(1, 3, (3,3))
arr2 = np.random.randint(1, 3, (3,3))

In [ ]:
arr1

array([[2, 1, 2],
       [1, 2, 2],
       [1, 1, 2]])

In [ ]:
arr1.flatten() #Return a copy of the array collapsed into one dimension.

array([2, 1, 2, 1, 2, 2, 1, 1, 2])

In [ ]:
#expand dimesnion
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [ ]:
arr.ndim

1

In [ ]:
np.expand_dims(arr, axis = 0) #increases the dimension by 1 at provoided axis

array([[1, 2, 3, 4]])

In [ ]:
np.expand_dims(arr, axis = 1)

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
np.expand_dims(arr, axis = 1).ndim

2

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
arr = np.zeros((3, 4))

In [ ]:
arr.ndim

2

In [ ]:
np.expand_dims(arr, axis=0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.expand_dims(arr, axis=1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [ ]:
np.expand_dims(arr, axis=0).ndim

3

In [ ]:
a = np.array([[1], [2], [3]])

In [ ]:
a

array([[1],
       [2],
       [3]])

In [ ]:
a.ndim

2

In [ ]:
np.squeeze(a) #Remove axes of length one from `a`

array([1, 2, 3])

In [ ]:
a

array([[1],
       [2],
       [3]])

In [ ]:
np.repeat(a, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [ ]:
arr1

array([[2, 1, 2],
       [1, 2, 2],
       [1, 1, 2]])

In [ ]:
np.repeat(arr1, 2)

array([2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2])

In [ ]:
np.repeat(arr1, 2, axis=0)

array([[2, 1, 2],
       [2, 1, 2],
       [1, 2, 2],
       [1, 2, 2],
       [1, 1, 2],
       [1, 1, 2]])

In [ ]:
np.repeat(arr1, 3, axis=0)

array([[2, 1, 2],
       [2, 1, 2],
       [2, 1, 2],
       [1, 2, 2],
       [1, 2, 2],
       [1, 2, 2],
       [1, 1, 2],
       [1, 1, 2],
       [1, 1, 2]])

In [ ]:
np.repeat(arr1, 3, axis=1)

array([[2, 2, 2, 1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2, 2, 2, 2],
       [1, 1, 1, 1, 1, 1, 2, 2, 2]])

In [ ]:
a

array([[1],
       [2],
       [3]])

In [ ]:
np.roll(a, -1)

array([[2],
       [3],
       [1]])

In [ ]:
np.roll(a, -2)

array([[3],
       [1],
       [2]])

In [ ]:
c = np.array([[1,2], [3, 4], [5,6], [7,8]])

In [ ]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.roll(c, 2)

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.roll(c, 2, axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [ ]:
arr1

array([[2, 1, 2],
       [1, 2, 2],
       [1, 1, 2]])

In [ ]:
arr2

array([[1, 2, 2],
       [2, 1, 2],
       [1, 1, 2]])

In [ ]:
arr1 + arr2

array([[3, 3, 4],
       [3, 3, 4],
       [2, 2, 4]])

In [ ]:
arr1-arr2

array([[ 1, -1,  0],
       [-1,  1,  0],
       [ 0,  0,  0]])

In [ ]:
arr1 * arr2

array([[2, 2, 4],
       [2, 2, 4],
       [1, 1, 4]])

In [ ]:
arr1 > arr2

array([[ True, False, False],
       [False,  True, False],
       [False, False, False]])

In [ ]:
arr1

array([[2, 1, 2],
       [1, 2, 2],
       [1, 1, 2]])

In [ ]:
~arr1

array([[-3, -2, -3],
       [-2, -3, -3],
       [-2, -2, -3]])

In [ ]:
#operations on numpy string array

In [ ]:
d = np.array(["pw", "skills"])

In [ ]:
d

array(['pw', 'skills'], dtype='<U6')

In [ ]:
np.char.upper(d)

array(['PW', 'SKILLS'], dtype='<U6')

In [ ]:
np.char.capitalize(d)

array(['Pw', 'Skills'], dtype='<U6')

In [ ]:
#mathematical functions

In [ ]:
arr1

array([[2, 1, 2],
       [1, 2, 2],
       [1, 1, 2]])

In [ ]:
np.sin(arr1)

array([[0.90929743, 0.84147098, 0.90929743],
       [0.84147098, 0.90929743, 0.90929743],
       [0.84147098, 0.84147098, 0.90929743]])

In [ ]:
np.cos(arr1)

array([[-0.41614684,  0.54030231, -0.41614684],
       [ 0.54030231, -0.41614684, -0.41614684],
       [ 0.54030231,  0.54030231, -0.41614684]])

In [ ]:
np.tan(arr1)

array([[-2.18503986,  1.55740772, -2.18503986],
       [ 1.55740772, -2.18503986, -2.18503986],
       [ 1.55740772,  1.55740772, -2.18503986]])

In [ ]:
np.log10(arr1)

array([[0.30103, 0.     , 0.30103],
       [0.     , 0.30103, 0.30103],
       [0.     , 0.     , 0.30103]])

In [ ]:
np.exp(arr1)

array([[7.3890561 , 2.71828183, 7.3890561 ],
       [2.71828183, 7.3890561 , 7.3890561 ],
       [2.71828183, 2.71828183, 7.3890561 ]])

In [ ]:
np.power(arr1, 3)

array([[8, 1, 8],
       [1, 8, 8],
       [1, 1, 8]])

In [ ]:
np.mean(arr1)

1.5555555555555556

In [ ]:
np.max(arr1)

2

In [ ]:
np.min(arr1)

1

In [ ]:
np.std(arr1)

0.4969039949999533

In [ ]:
np.var(arr1)

0.2469135802469136

In [ ]:
arr1-arr2

array([[ 1, -1,  0],
       [-1,  1,  0],
       [ 0,  0,  0]])

In [ ]:
np.subtract(arr1, arr2)

array([[ 1, -1,  0],
       [-1,  1,  0],
       [ 0,  0,  0]])

In [ ]:
arr1 *arr2

array([[2, 2, 4],
       [2, 2, 4],
       [1, 1, 4]])

In [ ]:
np.multiply(arr1, arr2)

array([[2, 2, 4],
       [2, 2, 4],
       [1, 1, 4]])

In [ ]:
np.mod(arr1, arr2) #return elment wise remainder

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 0]])

In [ ]:
np.sqrt(arr1)

array([[1.41421356, 1.        , 1.41421356],
       [1.        , 1.41421356, 1.41421356],
       [1.        , 1.        , 1.41421356]])

In [ ]:
#sort search

e = np.array([5, 6, 1, 2])

In [ ]:
e

array([5, 6, 1, 2])

In [ ]:
np.sort(e)

array([1, 2, 5, 6])

In [ ]:
f = np.array([5, 199, 200, 6, 7, 8])

In [ ]:
f

array([  5, 199, 200,   6,   7,   8])

In [ ]:
np.sort(f)

array([  5,   6,   7,   8, 199, 200])

In [ ]:
np.searchsorted(f, 170) #Find indices where elements should be inserted to maintain order.

6

In [ ]:
f = np.array([5, 199, 200, 6, 7, 0, 0, 0, 8])

In [ ]:
f

array([  5, 199, 200,   6,   7,   0,   0,   0,   8])

In [ ]:
np.count_nonzero(f)

6

In [ ]:
f[f > 0]

array([  5, 199, 200,   6,   7,   8])

In [ ]:
np.where(f>0)

(array([0, 1, 2, 3, 4, 8]),)

In [ ]:
np.extract(f>0, f)

array([  5, 199, 200,   6,   7,   8])

In [ ]:
f

array([  5, 199, 200,   6,   7,   0,   0,   0,   8])

In [ ]:
f.byteswap()

array([  360287970189639680, -4107282860161892352, -4035225266123964416,
         432345564227567616,   504403158265495552,                    0,
                          0,                    0,   576460752303423488])

In [ ]:
#matrix>> 2d array

import numpy.matlib as nm

In [ ]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [ ]:
nm.ones((3, 4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#numpy linear algebra

arr1 = np.random.randint(1, 10, (3, 3))
arr2 = np.random.randint(1, 10, (3, 3))

In [ ]:
arr1

array([[4, 5, 3],
       [6, 7, 4],
       [6, 5, 8]])

In [ ]:
arr2

array([[8, 1, 9],
       [6, 5, 4],
       [9, 7, 6]])

In [ ]:
arr1 @ arr2

array([[ 89,  50,  74],
       [126,  69, 106],
       [150,  87, 122]])

In [ ]:
arr1

array([[4, 5, 3],
       [6, 7, 4],
       [6, 5, 8]])

In [ ]:
np.linalg.det(arr1)

-12.000000000000016

In [ ]:
np.linalg.inv(arr1)

array([[-3.        ,  2.08333333,  0.08333333],
       [ 2.        , -1.16666667, -0.16666667],
       [ 1.        , -0.83333333,  0.16666667]])

In [ ]:
a = np.array([[7, 5.3, -3], [3, -5, 2], [5, 3, -7]])

In [ ]:
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [ ]:
b = np.array([16, 8, 0])

In [ ]:
b

array([16,  8,  0])

In [ ]:
np.linalg.solve(a, b)

array([2.59630607, 0.84432718, 2.21635884])